baseURL = "https://laura-lin.github.io/"
languageCode = "en-us"
title = "Yulu (Laura) Lin"
theme = "aafu"



[params]
    title = "Yulu (Laura) Lin"
    author = "Laura"
    description = "personal website"
    copyright = ""
    disableBlog = true

    [params.theme]
        # Available themes are 'light', 'dark', 'ocean', and 'pinkish'
        mainTheme = "pinkish"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = true
        singlePage = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Yulu (Laura) Lin"
        tagline = "UX Researcher"
        location = "Sunnyvale, CA"
        photo = "p1.JPG"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            icon = "fab fa-linkedin-in"
            url = "https://www.linkedin.com/in/lauralin-123/"
            title = "LinkedIn"		
        [[params.social.list]]
            icon = "fab fa-github"
            url = "https://github.com/laura-lin/laura-lin.github.io"
            title = "GitHub"
        [[params.social.list]]
            icon = "fab fa-twitter"
            url = "https://twitter.com/lauralinyulu"
            title = "Twitter"
        [[params.social.list]]
            icon = "fab fa-medium"
            url = "https://laurayulu.medium.com/"
            title = "Medium"
        [[params.social.list]]
            icon = "fab fa-instagram"
            url = "https://www.instagram.com/laura_lluu/"
            title = "instagram"		

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "Hi, this is Laura. I am a junior researcher at Stanford HCI Group. I am passionate about using mixed methods to conduct human behavioral research for cutting-edge products in autonomous vehicles/medical devices/ARVR"

    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "researcher"
            dates = "2021 - *Present*"
            company = "Stanford HCI Group"
            details = "Conducted eye-tracking environment; usability testing"
        [[params.experience.list]]
            position = "researcher"
            dates = "2021-present"
            company = "Harvard Medical School(Collab with ERI)"
        [[params.experience.list]]
            position = "research assistant"
            dates = "2020-2021"
            company = "Harvard University, Department of Psychology"

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "Master in Public Policy"
            college = "University of Minnesota-Twin Cities"
            dates = "2018 - 2020"

    # Publication section
    [params.publication]
        title = "Publications"
        icon = "fas fa-book"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["date", "authors", "title", "Journal"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        types = ["Conference Articles"]

        [[params.publication.list]]
            title = "Mindful People's Preference for Different Services of Autonomous Vehicles in China"
            authors = "Y Lin, G Jin"
            date = "2021"
            Journal = "2021 International Symposium on Connected and Autonomous Vehicles (SCoV 2021)"
            url = "#"
            type = "Conference Articles"
		
        [[params.publication.list]]
            title = "People’s Preferences for Different Uses of Autonomous Vehicles in China"
            authors = "Y Lin, G Jin"
            date = "2021"
            Journal = "2021 International Conference on Vehicle Technology and Intelligent Transport Systems(VEHITS 2021)"
            url = "#"
            type = "Conference Articles"

    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "People's Preferences for Different Uses of Autonomous Vehicles in China"
            url = "#"
            description = "people’s mindfulness score,  trust, health situations, travel costs, knowledge of autonomous vehicles, and their willingness to change their travel mode are significantly related to their choosing autonomous paratransit as their preferred mode. Policymakers can focus on providing enough information about autonomous vehicles’ prices for people with low income and high travel costs. When design autonomous vehicles, people with high mindfulness level will be more acceptable to paratransit services."
        [[params.project.list]]
            title = "Autonomous vehicles and visually impaired people's interaction"
            url = "#"
            description = "This project is an ongoing work about visually impaired people and autonomous vehicles' interaction. Researchers want to know how can visually impaired people need when they use autonomous vehicles in the future."
        [[params.project.list]]
            title = "Mindful people's preferences on autonomous vehicles"
            url = "#"
            description = "people’s mindfulness score,  trust, health situations, travel costs, knowledge of autonomous vehicles, and their willingness to change their travel mode are significantly related to their choosing autonomous paratransit as their preferred mode. "
        [[params.project.list]]
            title = "Eye tracking and driving behavior"
            url = "#"
            description = "We are exploring the correlations between drivers' eye movements and their creativity/stress level while driving "

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Python, R, Javascript"
            skillrating = 70
        [[params.skill.list]]
            skill = "Survey design"
            skillrating = 80
        [[params.skill.list]]
            skill = "User testing"
            skillrating = 90
        [[params.skill.list]]
            skill = "User interview"
            skillrating = 90
        [[params.skill.list]]
            skill = "Litereture Review"
            skillrating = 100
        

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"

        [[params.hobby.list]]
            hobby = "Cooking"
        [[params.hobby.list]]
            hobby = "Hiking"
        [[params.hobby.list]]
            hobby = "Baking"

    [params.menu]
        [[params.menu.list]]
            dir = "portfolio"
            label = "Portfolio"